### ISSUE TITLE
Login issue with new account

### ISSUE THREAD

**Issue by oeway** [bioimage-io/bioimageio-chatbot#110]
It appears that we some some issue with user login on linux on either chrome or firefox.

The first time I visited https://bioimage.io/chat/ I received an error:

`{"detail":"Not Found"}`
together with a centered spinning animation, which persisted indefinitely.

Reloading the page, I received a login prompt. I created an account successfully (which appears to have used the [hypha.eu.auth0.com](http://hypha.eu.auth0.com/) service). Then when I click the blue Login button, I needed to allow popups, then I receive a new login screen with header "Hypha Account" and blue "Login/Sign up" button, which when clicked, brings up another popup, where I am finally able to enter my new username and password. However, after doing so, the popup closes, and I am left on the second "Hypha Account" tab. Back on the original "Bioimage.IO Chatbot" tab, I receive a JS popup dialog with text:
```
Failed to login, please reload the page and try again, error:Error: Traceback (most recent call last):
^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/hypha/core/auth.py", line 440, in check_login
raise Exception("Login timeout")
Exception: Login timeout
```

Reported by @ctrueden

**Comment by ctrueden** [comment]
OK, after further testing, I believe the issue is use of newly created credentials (imjoy.eu.auth0.com?) versus GitHub-based authentication. I tested further on macOS and was able to reproduce the above problem when logging in with my newly created credentials with email `ctrueden@wisc.edu` (Firefox browser), but I *am* able to log in using GitHub-based authentication. Then on Linux, I cleared all browser cache relating to bioimage.io and auth0.com, and tried a fresh login using GitHub-based credentials, and it worked. So I suggest to change the title of this issue accordingly.

**Comment by ctrueden** [comment]
As a short-term solution, I would suggest to remove the option to register new accounts, in favor of promoting only the GitHub- and Google-based login methods, since they are the only functional paths for new users right now.

**Comment by oeway** [comment]
> in favor of promoting only the GitHub- and Google-based login methods, since they are the only functional paths for new users right now.

Good idea, I have now disabled the registration for now.
<img width="533" alt="Screenshot 2024-06-05 at 16 13 04" src="https://github.com/bioimage-io/bioimageio-chatbot/assets/478667/e459a9e5-93eb-49c1-908a-b99d71baf134">
