### ISSUE TITLE
How to see the script used in a Bridget mode response?

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#113]
I know you can click the Details pane to see the raw JSON, which includes the script, but it's in single-line escaped format, which one would then need to decode in order to reuse it outside the browser. Could a way be added to display the script(s) in their raw original form?

**Comment by oeway** [comment]
Thanks for the suggestion, I have now improved the display for details now, for example
<img width="974" alt="Screenshot 2024-06-04 at 15 53 20" src="https://github.com/bioimage-io/bioimageio-chatbot/assets/478667/173c3de1-abb1-41b2-90b8-a7a6ce7055ae">

Fixed by https://github.com/bioimage-io/bioimageio-chatbot/commit/cdf0b0af57ade812a08b77597849400ed91b8d4c
