### ISSUE TITLE
Remounting data folder after local changes does not see them

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#116]
I mounted a data folder with three subfolders. I then created a fourth folder inside the data folder, and asked Bridget to list the contents of my data folder, and the fourth folder was not shown. I tried the Mount Files again to remount, and Bridget stated that the data folder was mounted successfully, but it still was unaware of the fourth folder.

I tried also simply adding a new file (not folder), and the chatbot cannot see it, even after remounting. Hitting Ctrl+R to reload the chatbot completely and then mounting again does work.

**Comment by ctrueden** [comment]
In another attempt, remounting with Mount Files again *does* see the new data. So this issue may be intermittent.

**Comment by oeway** [comment]
This issue is related how we handle sync/async file system in pyodide.

Basically, the browser file system api is only asynchronous, but pyodide python native file operations are synchronous, to let pyodide operate the folder mounted using the browser file system api, pyodide will mirror the file system in memory, then allow writing memory file in synchronous manner, this means newly written files are only in memory until we manually call the syncfs()function. One side effect of this function is that it will copy the files previously stored in memory plus newly created files to overwrite the entire mounted folder.

As a result, if you first mount the folder, pyodide make a copy of the files into memory, then if you manually add some files into that same folder, it will be removed when pyodide executed some code and synchronize the files back to disk (currently we just call syncfs() right after script execution: https://github.com/bioimage-io/bioimage.io/blob/1082db9471722406e6ecd51a0b57ce4f6861e174/public/chat/pyodide-worker.js#L252)

This is a relevant issue: https://github.com/pyodide/pyodide/issues/3456

I might have a solution, since the `syncfs()` function can take a populate argument: https://github.com/pyodide/pyodide/blob/b177dba277350751f1890279f5d1a9096a87ed13/src/js/nativefs.ts#L24
Let me try to fix this.

**Comment by ctrueden** [comment]
@oeway Thanks for addressing this so quickly! Unfortunately, with today's edition of the chatbot, I am now unable to mount files at all. The Mount Files button appears a few moments after switching to Bridget, but then clicking it does nothing. Should I reopen here, or open a new issue?

**Comment by oeway** [comment]
> @oeway Thanks for addressing this so quickly! Unfortunately, with today's edition of the chatbot, I am now unable to mount files at all. The Mount Files button appears a few moments after switching to Bridget, but then clicking it does nothing. Should I reopen here, or open a new issue?

Hi oh, that's sounds wired, I just tried it and cannot reproduce, can you open https://bioimage.io/chat/?assistant=Bridget and see if there is any error in the browser console?

**Comment by ctrueden** [comment]
Yep! When I click the Mount Files button, the console spits out:
```
Uncaught (in promise) ReferenceError: showDirectoryPicker is not defined
    setupCodeInterpreter https://bioimage.io/chat/?assistant=Bridget:1142
    jQuery 2
```
But that's in Firefox. Whereas in Chromium, the button still works.

**Comment by oeway** [comment]
> But that's in Firefox. Whereas in Chromium, the button still works.

Aha, that make sense then, we used the File System Access api which is only available in Chrome.

For that reason, you should see a warning in Firefox or other browsers:

> Warning! The code interpreter is only supported in Chromium based browsers (e.g. Chrome, Edge, Brave, etc.), please use a Chromium based browser to use the code interpreter.

**Comment by ctrueden** [comment]
> Warning! The code interpreter is only supported in Chromium based browsers (e.g. Chrome, Edge, Brave, etc.), please use a Chromium based browser to use the code interpreter.

OK. But in my tests, the code interpreter *does* work in Firefox (#126), whereas it's the Mount Data button that does not work. Perhaps the warning text should be changed accordingly?

**Comment by oeway** [comment]
Right! Fixed here: https://github.com/bioimage-io/bioimage.io/commit/06cdac3205027cbbc3d97769ce1335798d2538a9

**Comment by ctrueden** [comment]
I just tested today's chatbot in Chromium on Linux, and not only is this bug solved, but it now seems that when I drop in additional files to an already-mounted data folder, it *sees them immediately* rather than needing to remount the folder. That's awesome! :tada:
