### ISSUE TITLE
Chatbot can overwrite detailed helpful responses with less detailed/helpful ones

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#117]
I loaded a 4D image, then asked "Please display the image with interactive sliders for Z and T." It tried to use `ipywidgets` (a very reasonable thing to do), but it doesn't work in Pyodide, only Jupyter. I noticed that immediately after failing, it printed out several helpful paragraphs explaining that it failed due to limitations of the environment, and encouraging me to try it in Jupyter Notebook, including instructions on which packages to install, and which script snippet to run. :+1:

Unfortunately, before I could fully digest the information, it began regenerating a different response, overwriting the old one. This second final response was much shorter, only a single paragraph, as follows:

> Due to the limitations of the current environment, interactive widgets like ipywidgets cannot be directly used here. However, you can achieve the desired functionality of displaying the image with interactive sliders for Z and T dimensions on your local machine using Jupyter Notebooks or JupyterLab. I've provided guidance on how to set this up and the code you'll need. If you have any further questions or need additional assistance, please let me know!

But since the guidance in question was overwritten, the user is no longer able to see it, or act on the advice. The "More Details" pane only shows "step-0" with a short JSON including encoded failing script, brief thoughts/reasoning, and resultant stack trace—the original response has been lost.

**Comment by oeway** [comment]
In general this issue is mainly due to the actual behavior of openai model, I have now upgraded the model to `gpt-4o`, and also made a few other enhancement, now it should be much better:

<img width="1183" alt="Screenshot 2024-06-04 at 19 07 23" src="https://github.com/bioimage-io/bioimageio-chatbot/assets/478667/fd69e5f8-835f-479b-9ec9-f1de5e806b78">

I will close this for now, please feel free to reopen if it occurs again.
