### ISSUE TITLE
"Local" chatbot bootstrapping still goes through remote bioimage.io server

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#124]
When running a local server, why is it necessary to bootstrap the UI through the bioimage.io/chat web page—i.e. https://bioimage.io/chat/?server=http://127.0.0.1:9000 vs http://127.0.0.1:9000 for the URL? If bioimage.io is down, it means no one can use their "local" chatbot unless they have a cached version of the page, right? Why not bundle the needed web resources with the bioimageio-chatbot package, so that this extra remote dependency is not needed? Analytics?

Furthermore, I received a login prompt today when opening up my "local" server again. Why do I need to log in to use my local server?

**Comment by oeway** [comment]
Hi, we had it under bioimage.io mainly because it's a static website hosted at github pages, it should go down very rarely, and also to make it easier to work with our login system (protected by a whitelisted client domain). To support fully locally available client (although it won't mean much since it still requires internet access to talk to openai), we have take back the client code to this repo and setup a CI to deploy it automatically instead.
