### ISSUE TITLE
Clarify the ramifications of "mounting" a local data folder

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/bioimageio-chatbot#127]
I mounted a data folder with >10GB of image data, and it seemed to work fine, but... it is not clear to me exactly what is getting uploaded to the remote server when, and under what circumstances files will be downloaded back to the local. I also don't know how performant this is... does it always redownload everything, or is smart about only downloading things that have changed. For deletions, does it delete local files if they were deleted on the remote? What if something goes wrong during the initial upload of files to the server—are my local files at risk of being inadvertently deleted since they then appear to be "missing" from the remote? As you can see, I have many questions. :sweat_smile: 

So I'm wondering if it makes sense to:
* Add a clearer explanation, perhaps hidden under a collapsed Details pane, about what happens when you mount a folder.
* Add the ability to mount two separate folders: an input/read-only folder and an output/read-write folder, to ensure original data cannot be corrupted if the chatbot loop goes in an unexpected direction (if so, perhaps this idea should be a separate issue).
* Add an explicit Sync button (or even two buttons, Upload vs Download) to give the user more control about when data is transferred to/from the chatbot.

What do you think?

**Comment by oeway** [comment]
Hi, thanks for the question, these are really good ones, which we kind of naturally assume users will know.
For your question, the data remains in your browser, it won't be uploaded anywhere (although the browser warns the upload), and the code interpreter runs entirely in your browser too, so no data files will be uploaded or downloaded when processing. Nevertheless, the print messages from the code interpreter will be send to the chatbot server to decide the next step or create a response to the user.

I just added a message which will show up when the mounting data folder feature is enabled: https://github.com/bioimage-io/bioimage.io/commit/ac196cc575c573b89461ef24c1237eeae3ac3317

Including a warning about making backup before mounting data folder. Normally, data loss should not happen, however, because it's the LLM controls the code, it may make mistake and cause data loss, so I think the best way forward is to warn the user anyway that their data may lose so they need to always keep a backup.

What do you think?

**Comment by ctrueden** [comment]
The new explanations and warning look great! Very helpful.
